version: '2'
services:
  nginx-auto-conf:
    image: ipepe/nginx-auto-conf-serving
    ports:
      - "8080:80"
      - "8022:22"
    volumes:
      - ./data/webapps:/usr/share/webapps

# docker-compose -f docker-compose.dev.yml up --build